name: 'Maven GAV Extractor'

author: stevei5mc
description: 'Get files hash action'

branding:
  icon: 'file-text'
  color: 'orange'

inputs:
  targetFilesPath:
    description: 'Target file path'
    required: true
  hashListFileSaveName:
    description: 'Hash list file save name'
    required: true
    default: "target"
  hashFileFileSavePath:
    description: "Hash list file save path"
    required: true
  getMd5:
    description: "Get files hash for md5"
    required: false
    default: 'true'
  getSha1:
    description: "Get files hash for sha1"
    required: false
    default: 'true'
  getSha256:
    description: "Get files hash for sha256"
    required: false
    default: 'true'
  getSha512:
    description: "Get files hash for sha512"
    required: false
    default: 'true'
  printHashToHashListFileName:
    description: "Print Hash to hash list file name"
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Print inputs info
      shell: bash
      run: |
        echo Target file path: ${{ inputs.targetFilesPath }}
        echo Hash list file save name: ${{ inputs.hashListFileSaveName }}
        echo Hash list file save path: ${{ inputs.hashFileFileSavePath }}
        echo Get Md5: ${{ inputs.getMd5 }}
        echo Get Sha1: ${{ inputs.getSha1 }}
        echo Get Sha256: ${{ inputs.getSha256 }}
        echo Get Sha512: ${{ inputs.getSha512 }}
        echo Print Hash to hash list file name: ${{ inputs.printHashToHashListFileName }}
    - name: "Get files md5"
      shell: bash
      if: ${{ inputs.getMd5 }}
      run: |
        hashListFiles=${{ inputs.hashFileFileSavePath }}/${{ inputs.hashListFileSaveName }}.txt
        echo ==================== Start get md5 ====================
        md5sum ${{ inputs.targetFilesPath }} | tee "$hashListFile".txt
        if [ "${{ inputs.printHashToHashListFileName }}" == "true" ]; then
        hashListFilesHash=$(md5sum "$hashListFiles"|awk '{print $1}')
        hashListFileName2=${{ inputs.hashListFileSaveName }}-md5-$hashListFilesHash.txt
        hashListFile2=${{ inputs.hashFileFileSavePath }}/$hashListFileName2.txt
        mv "$hashListFiles" "$hashListFiles2"
        fi
        echo ==================== Md5 get over ====================
    - name: "Get files Sha1"
      shell: bash
      if: ${{ inputs.getSha1 }}
      run: |
        hashListFiles=${{ inputs.hashFileFileSavePath }}/${{ inputs.hashListFileSaveName }}.txt
        echo ==================== Start get Sha1 ====================
        sha1sum ${{ inputs.targetFilesPath }} | tee "$hashListFile".txt
        if [ "${{ inputs.printHashToHashListFileName }}" == "true" ]; then
        hashListFilesHash=$(sha1sum "$hashListFiles"|awk '{print $1}')
        hashListFileName2=${{ inputs.hashListFileSaveName }}-sha1-"$hashListFilesHash".txt
        hashListFile2=${{ inputs.hashFileFileSavePath }}/"$hashListFileName2".txt
        mv "$hashListFiles" "$hashListFiles2"
        fi
        echo ==================== Sha1 get over ====================
    - name: "Get files Sha256"
      shell: bash
      if: ${{ inputs.getSha256 }}
      run: |
        hashListFiles=${{ inputs.hashFileFileSavePath }}/${{ inputs.hashListFileSaveName }}.txt
        echo ==================== Start get Sha256 ====================
        sha256sum ${{ inputs.targetFilesPath }} | tee "$hashListFile".txt
        if [ "${{ inputs.printHashToHashListFileName }}" == "true" ]; then
        hashListFilesHash=$(sha256 "$hashListFiles"|awk '{print $1}')
        hashListFileName2=${{ inputs.hashListFileSaveName }}-sha256-"$hashListFilesHash".txt
        hashListFile2=${{ inputs.hashFileFileSavePath }}/"$hashListFileName2".txt
        mv "$hashListFiles" "$hashListFiles2"
        fi
        echo ==================== Sha256 get over ====================
    - name: "Get files Sha512"
      shell: bash
      if: ${{ inputs.getSha512 }}
      run: |
        hashListFiles=${{ inputs.hashFileFileSavePath }}/${{ inputs.hashListFileSaveName }}.txt
        echo ==================== Start get Sha512 ====================
        sha512sum ${{ inputs.targetFilesPath }} | tee "$hashListFile".txt
        if [ "${{ inputs.printHashToHashListFileName }}" == "true" ]; then
        hashListFilesHash=$(sha512 "$hashListFiles"|awk '{print $1}')
        hashListFileName2=${{ inputs.hashListFileSaveName }}-sha512-"$hashListFilesHash".txt
        hashListFiles2=${{ inputs.hashFileFileSavePath }}/"$hashListFileName2".txt
        mv "$hashListFiles" "$hashListFiles2"
        fi
        echo ==================== Sha512 get over ====================