name: CI

on:
  push:
  pull_request:

jobs:
  Test :
    strategy:
      matrix:
        include: [
          {name: "ubuntu",os: ubuntu-latest},
          {name: "windows",os: windows-latest}
          #{name: "macos",os: macos-latest}
        ]
    runs-on: ${{ matrix.os }}
    name: Test for ${{ matrix.name }}
    steps:
    - uses: actions/checkout@v4
    - name: Download for Kazumi 1.5.3
      uses: robinraju/release-downloader@v1.11
      with:
        repository: 'Predidit/Kazumi'
        tag: '1.5.3'
        fileName: '*'
        out-file-path: 'test'
    - name: Download for Kazumi 1.5.4
      uses: robinraju/release-downloader@v1.11
      with:
        repository: 'Predidit/Kazumi'
        tag: '1.5.4'
        fileName: '*'
        out-file-path: 'test'
    - name: Download for Kazumi 1.5.5
      uses: robinraju/release-downloader@v1.11
      with:
        repository: 'Predidit/Kazumi'
        tag: '1.5.5'
        fileName: '*'
        out-file-path: 'test'
    - run: ls -la test
      shell: bash
    - name: 获取文件hash
      uses: ./
      with:
        targetFilesPath: './test/*.*'
        hashListFileSaveName: 'TEST'
        hashFileFileSavePath: './hash-files'
        getSha1: false
    - name: 收集构建文件
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Test-${{ runner.os }}_${{ github.run_number}}
        path: hash-files
